FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache wget openssl libc6-compat
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY src ./src
EXPOSE 3005
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && npm run dev"]
