-- AlterTable
ALTER TABLE "School" ADD COLUMN "nameEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "School" ADD COLUMN "website" TEXT NOT NULL DEFAULT '';
ALTER TABLE "School" ADD COLUMN "contact" TEXT NOT NULL DEFAULT '';
