-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'ADMIN',
    "refreshToken" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "School" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "province" TEXT NOT NULL,
    "affiliation" TEXT NOT NULL,
    "level" TEXT NOT NULL,
    "logoUrl" TEXT,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "School_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Score" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "a1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "a2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "a3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "a4" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "a5" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "b1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "b2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "b3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "b4" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "b5" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "c1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "c2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "c3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "c4" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "c5" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "d1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "d2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "d3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "d4" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "d5" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "e1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "e2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "e3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "e4" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "e5" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Score_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Ranking" (
    "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text,
    "schoolId" TEXT NOT NULL,
    "scoreA" DOUBLE PRECISION NOT NULL,
    "scoreB" DOUBLE PRECISION NOT NULL,
    "scoreC" DOUBLE PRECISION NOT NULL,
    "scoreD" DOUBLE PRECISION NOT NULL,
    "scoreE" DOUBLE PRECISION NOT NULL,
    "totalScore" DOUBLE PRECISION NOT NULL,
    "level" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Ranking_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Score_schoolId_key" ON "Score"("schoolId");

-- CreateIndex
CREATE UNIQUE INDEX "Ranking_schoolId_key" ON "Ranking"("schoolId");

-- AddForeignKey
ALTER TABLE "Score" ADD CONSTRAINT "Score_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ranking" ADD CONSTRAINT "Ranking_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
